name = "iosys"
main = "src/worker.js"
compatibility_date = "2024-02-03"
account_id = "1966c03f4aadbbe46523c450e7c71c51"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "inward-outward-db"
database_id = "65cdca58-f391-42fd-b314-2bdf52aa6a19"

# Cron: Every Saturday at 11:00 AM IST (05:30 UTC)
[triggers]
crons = ["30 5 * * 6"]
